config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :collections
  resources :museums
  resources :artists
  resources :artworks do 
	member do
		get 'add_to_collection'
		end
	end 
  resources :users, only: [:show]
	
  root to: 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :artworks
	accepts_nested_attributes_for :artworks
end

app/models/artwork.rb
class Artwork < ApplicationRecord
	belongs_to :artist
	belongs_to :user

end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :inventories
	has_many :artworks, through: :inventories
	belongs_to :museum 
end

app/models/group.rb
class Group < ApplicationRecord
	

end

app/models/inventory.rb
class Inventory < ApplicationRecord
	belongs_to :collection
	belongs_to :artwork

end

app/models/museum.rb
class Museum < ApplicationRecord
has_many :teams
has_many :users, through: :teams
has_many :collections
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :museum
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	validates :email, presence: true, uniqueness: true
	
	has_many :teams
	has_many :museums, through: :teams
	has_many :artworks

	
	
	def can_manage?(collection)
		museum = collection.museum
		museum.users.find_by(id: 1) ? true : false
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
	include DeviseWhitelist
	

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def new 
		@artist = Artist.new
		@artist.artworks.build
		current_user.artworks.build
		@artworks = Artwork.all
	end 

	#Implement a find or create where the user has to select an artist or create one
	def create
		artist = Artist.create(artist_params)
		artwork = artist.artworks.last
		artwork.user = current_user
		artist.save
		redirect_to artist_path(artist)
	end 

	def show 
		@artist = Artist.find_by(id:params[:id])
	end 

	def edit
		@artist = Artist.find_by(id:params[:id])
	end 


 private 

	def artist_params 
		params.require(:artist).permit(
			:full_name,
			:biography,
			:birth_date,
			:death_date,
			:style,
			artworks_attributes: [
				:user_id,
				:title,
				:price,
				:technic
				]
		)
	end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

	def index
		@artworks = Artwork.all
	end

	def new
		
		@artwork = Artwork.new
		@artist = Artist.new
		current_user.artworks.build
	end 

	def create
		
		@artwork = Artwork.create(artwork_params)

		unless params[:artist][:full_name].empty?
			artist = @artwork.create_artist(params[:artist])
		end

		@artwork.save

		redirect_to user_path(current_user)
	end 

	def show
		@artwork = Artwork.find_by(id:params[:id])
		@collections = Collection.all.select{|c| current_user.can_manage?(c)}
	end 

	def edit
		@artwork = Artwork.find_by(id:params[:id])
	end

 private 

	def artwork_params 
		params.require(:artwork).permit(
			:title,
			:price,
			:technic,
			:user_id,
			artist_attributes: [
				:full_name,
				:biography,
				:birth_date,
				:death_date,
				:style
				]
			)
	end

end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
	def index 
		@museums = Museum.all
	end

	def new 
		@museum = Museum.new
	end 

	def create 
		museum = Museum.create(museum_params)
		museum.users << current_user
		redirect_to museum_path(museum)
	end

	def show 
		@museum = Museum.find_by(id:params[:id])
	end

	def edit 
		@museum = Museum.find_by(id:params[:id])
	end
	
	private 

		def museum_params 
			params.require(:museum).permit(
				:name, 
				:location,
				:specialty
			)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :verify_user_is_authenticated, only: [:new, :create]


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
	def show 
		@user = User.find_by(id: current_user.id)
	end



 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/artists/_form.html.erb
<h2>Add an artwork</h2>
	<%= form_for @artist do |f| %>
		<fieldset>

			<fieldset>
			<h3>About the artwork</h3>
				<%= f.fields_for :artworks do |a| %>
				<div class="form-group">
					<%= f.label :artist_id %>
					<%= f.collection_select :id, Artist.all, :id, :full_name, {:include_blank => true}, {class: "form-control"} %>
				</div>
				<div class="form-group">
					<%= a.label :title %>
					<%= a.text_field :title, class: "form-control" %>
				<div>
				<div class="form-group">
					<%= a.label :price %>
					<%= a.text_field :price, class: "form-control" %>
				<div>
				<div class="form-group">
					<%= a.label :technic %>
					<%= a.text_field :technic, class: "form-control" %>
				</div>
			</fieldset>
			<% end %>

			<h3>About the artist if is not in the list</h3>
			<div class="form-group">
				<%= f.label :full_name %>
				<%= f.text_field :full_name, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :biography %>
				<%= f.text_field :biography, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :birth_date, "Born" %>
				<%= f.date_field :birth_date, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :death_date, "Died" %>
				<%= f.date_field :death_date, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :style %>
				<%= f.text_field :style, class: "form-control" %>
			</div>
			
	 <%= f.submit "Add to my collection", class: "btn btn-primary" %>
		</fieldset>
	<% end %>

app/views/artists/edit.html.erb
<%= form_for @artist do |f| %>
	<%= f.label :full_name %>
	<%= f.text_field :full_name %>
	<br>
	<%= f.label :biography %>
	<%= f.text_field :biography %>
	<br>
	<%= f.label :birth_date %>
	<%= f.date_field :birth_date %>
	<br>
	<%= f.label :death_date %>
	<%= f.date_field :death_date %>
	<br>
	<%= f.label :style %>
	<%= f.text_field :style %>
	<br> 
	<%= f.submit "Add to my collection" %>
<% end %>

app/views/artists/index.html.erb
<div class="col-md-6">
  <div class="mt-4">
    <h1>Artists</h1>
  </div>
    <div class="row row-cols-3">
      <% @artists.each do |artist| %>
      <div class="col">
        <div class="card mb-3">
          <h3 class="card-header"><%= link_to artist.full_name, artist_path(artist) %></h3>
          <div class="card-body">
            <h6 class="card-subtitle text-muted"><%= artist.style %></h6>
          </div>
          <img style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
            <div class="card-body">
              <p class="card-text"><%= artist.biography %></p>
            </div>
            <div class="card-footer text-muted">
              <%= artist.created_at %>
            </div>
          </div>
      </div>
      <% end %>
    </div>

</div>

app/views/artists/new.html.erb
<div class="col">

<%= render 'form' %>

</div>

app/views/artists/show.html.erb
<div class="col">

  <h1><%= @artist.full_name %></h1>
  <p><%= @artist.biography %></p>

  <ul><% @artist.artworks.each do |artwork| %>
	  <li><%= artwork.title %></li>
  </ul>
  <% end %>
     

</div>

app/views/artworks/_form.html.erb
<h2>Add an artwork</h2>
	<%= form_for @artwork do |f| %>
		<fieldset>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :artist_id %>
				<%= f.collection_select :artist_id, Artist.all, :id, :full_name, {:include_blank => true}, {class: "form-control"} %>
        </div>
			<div class="form-group">
				<%= f.label :price %>
				<%= f.text_field :price, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :technic %>
				<%= f.text_field :technic, class: "form-control" %>
			</div>
    <h3>Or create a new Artist</h3>
      <%= form_for @artist do |f| %>
      <fieldset>
        <div class="form-group">
          <%= f.label :full_name %>
          <%= f.text_field :full_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :biography %>
          <%= f.text_field :biography, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :birth_date, "Born" %>
          <%= f.date_field :birth_date, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :death_date, "Died" %>
          <%= f.date_field :death_date, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :style %>
          <%= f.text_field :style, class: "form-control" %>
        </div>
        <% end %>
			<%= f.submit "Add to my collection", class: "btn btn-primary" %>
 
		</fieldset>
	<% end %>

app/views/artworks/index.html.erb
<div class="col-md-6">
  <div class="mt-4">
    <h1>Artworks</h1>
  </div>
<div class="row row-cols-3">
  <% @artworks.each do |artwork| %>
  <div class="col">
    <div class="card mb-3">
      <h3 class="card-header">
        <%= link_to artwork.title, artwork_path(artwork) %>
      </h3>
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to artwork.artist.full_name, artist_path(artwork.artist) %>
        </h5>
        <h6 class="card-subtitle text-muted">
          <%= artwork.technic %>
        </h6>
      </div>
      <img style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
        <div class="card-body">
          <p class="card-text">Biography of this artist written in elegant language with a lot of details such as when the artist died, used to do for a living, had any child or wife.</p>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
  </div>
  <% end %>
</div>
</div>

app/views/artworks/new.html.erb
<div class="col">
  <%= render 'form' %>
</div>

app/views/artworks/show.html.erb
<div class="col">
  <div>
    <h1><%= @artwork.title %></h1>
    <p><strong>Author : </strong><%= @artwork.artist.full_name %></p>
    <p><strong>Price : </strong><%= @artwork.price %></p>
    <p><strong>Technic : </strong><%= @artwork.technic %></p>
    <p><strong>Currently belong to </strong><%= @artwork.user.name %> <%= @artwork.user.surname %>
  </p>
  </div>
  <br></br>
    <div>
      <h3>Add to collection</h3>
      <ul class="list-group">
        <% @collections.each do |c| %>
        <li class="list-group-item d-flex">
          <div class="mr-auto">
            <%= c.name %>
          </div>
            <span class="breadcrumb-item">
              <% if c.artworks.any? {|a| a.id == @artwork.id } %>            
              <%= link_to "remove", collection_path(c, artwork: @artwork.id), method: "patch" %>
              <% else %>            
              <%= link_to "add", collection_path(c, artwork: @artwork.id), method: "patch" %>
              <% end %>
            </span>
            <span class="breadcrumb-item">
             <%= link_to "View collection", collection_path(c) %>
            </span>
        </li>
        <% end %>
      </ul>
    </div>
</div>

app/views/museums/_form.html.erb
<%= form_for @museum do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<br>
	<%= f.label :specialty %>
	<%= f.text_field :specialty %>
	<br>
 <%= f.submit "Create" %>
<% end %>

app/views/museums/index.html.erb
  <div class="col-md-6">
    <div class="mt-4">
      <h1>Museums</h1>
    </div>
    <div class="row row-cols-3">
      <% @museums.each do |museum| %>
      <div class="col">
        <div class="card mb-3">
          <h3 class="card-header">
            <%= link_to museum.name, museum_path(museum) %>
          </h3>
          <div class="card-body">
            <h6 class="card-subtitle text-muted">
              <%= museum.specialty %>
              </h6>
          </div>
          <img style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
            <div class="card-body">
              <p class="card-text">
                <%= museum.name %>
              </p>
            </div>
            <div class="card-footer text-muted">
              <%= museum.location %>
            </div>
          </div>
      </div>
      <% end %>
    </div>

  </div>

app/views/museums/new.html.erb
<h1>Create museum</h1>

<%= render 'form' %>

app/views/museums/show.html.erb
<h1><%= @museum.name %></h1>
<p>Collections</p>
<ul>
  <% @museum.collections.each do |collection| %>
  <li>
    <%= collection.name %>
    </li>
    <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
   <br>
 <%= f.label :surname %>
 <%= f.text_field :surname %>
   <br>
 <%= f.label :email %>
 <%= f.text_field :email %>
   <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
 <%= f.label :address %>
 <%= f.text_field :address %>
   <br>
 <%= f.label :phone %>
 <%= f.text_field :phone %>
   <br>
 <%= f.label :position %>
 <%= f.text_field :position %>

 <%= f.label :group %>
 <%= f.collection_select :group, Group.all, :name, :name %>

 <%= f.submit "Sign up!"%>
 <% end %>

app/views/users/new.html.erb
<h1>Create user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="col">
  <div class="container">
        <div class="card border-light" style="max-width: 30rem;">
            <div class="card-header"><%= @user.name %> <%= @user.surname %></div>
            <div class="card-body">
              <h6 class="card-subtitle text-muted">User information</h6>
              <p class="card-text">
                <p><strong>Email :</strong> <%= @user.email %></p>
                <p><strong>Address :</strong> <%= @user.address %></p>
                <p><strong>Phone number :</strong> <%= @user.phone %></p>
                <p><strong>User type :</strong> <%= @user.group %></p>
                <p><strong>Occupation :</strong> <%= @user.position %></p>
              </p>
            </div>
        </div>
    <%= link_to "Manage or delete account", edit_user_registration_path %>
  </div>
  <div class="container">
        <br></br>
        <h2>
            <% if current_user == @user %>
          My arts
          <% else %>
          <%= @user.name.capitalize %>'s arts
            <% end %>
        </h2>

        <ul class="list-group">
          <% if @user.artworks.any? %>
              <% @user.artworks.each do |artwork| %>
                <li class="list-group-item d-flex justify-content-between align-items-center">    
                  <%= link_to artwork.title, artwork_path(artwork.id) %> by <%= artwork.artist.full_name %>
                </li>
              <% end %>
          <% else %>            
            <p>No artwork to display</p>
            <% end %>
        </ul>
          <% unless current_user != @user %>
            <%= link_to 'Add an art', new_artist_url %>
          <% end %>
      </div>
</div>