config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :collections
  resources :museums
  resources :artists
  resources :artworks do 
	member do
		get 'add_to_collection'
		end
	end 
  resources :users, only: [:show]
	
  root to: 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :artworks
	accepts_nested_attributes_for :artworks
end

app/models/artwork.rb
class Artwork < ApplicationRecord
	belongs_to :artist
	belongs_to :user

end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :inventories
	has_many :artworks, through: :inventories
	belongs_to :museum 
end

app/models/group.rb
class Group < ApplicationRecord
	

end

app/models/inventory.rb
class Inventory < ApplicationRecord
	belongs_to :collection
	belongs_to :artwork

end

app/models/museum.rb
class Museum < ApplicationRecord
has_many :teams
has_many :users, through: :teams
has_many :collections
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :museum
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	validates :email, presence: true, uniqueness: true
	
	has_many :teams
	has_many :museums, through: :teams
	has_many :artworks

	
	
	def can_manage?(collection)
		museum = collection.museum
		museum.users.find_by(id: 1) ? true : false
	end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def new 
		@artist = Artist.new
		@artist.artworks.build
		current_user.artworks.build
		@artworks = Artwork.all
	end 

	#Implement a find or create where the user has to select an artist or create one
	def create
		artist = Artist.create(artist_params)
		artwork = artist.artworks.last
		artwork.user = current_user
		artist.save
		redirect_to artist_path(artist)
	end 

	def show 
		@artist = Artist.find_by(id:params[:id])
	end 

	def edit
		@artist = Artist.find_by(id:params[:id])
	end 


 private 

	def artist_params 
		params.require(:artist).permit(
			:full_name,
			:biography,
			:birth_date,
			:death_date,
			:style,
			artworks_attributes: [
				:user_id,
				:title,
				:price,
				:technic
				]
		)
	end

end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
	def index 
		@museums = Museum.all
	end

	def new 
		@museum = Museum.new
	end 

	def create 
		museum = Museum.create(museum_params)
		museum.users << current_user
		redirect_to museum_path(museum)
	end

	def show 
		@museum = Museum.find_by(id:params[:id])
	end

	def edit 
		@museum = Museum.find_by(id:params[:id])
	end
	
	private 

		def museum_params 
			params.require(:museum).permit(
				:name, 
				:location,
				:specialty
			)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
	def show 
		@user = User.find_by(id: current_user.id)
	end



 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtworksManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

	  <!--NAV BAR-->
	  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	  <a class="navbar-brand" href="/">Artworks Manager</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarColor01">
		<ul class="navbar-nav mr-auto">
		  <li class="nav-item active">
			<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
		  </li>
		  <li class="nav-item">
			<%= link_to "Artworks", artworks_path, class: "nav-link" %>
		  </li>
		  <li class="nav-item">
			<%= link_to "Artists", artists_path, class: "nav-link" %>
		  </li>
		  <li class="nav-item">
			<%= link_to "Museums", museums_path, class: "nav-link" %>
		  </li>
		</ul>
		<% if current_user %>
		<%= button_to "My profil", user_path(current_user.id), method: :get, class: "btn btn-info btn-sm mr-2" %>
		<%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-sm" %>
		<% else %>
		<%= button_to "Log in", new_user_session_path, method: :get, class: "btn btn-primary btn-sm mr-2" %>
		<%= button_to "Register", new_user_registration_path, method: :get, class: "btn btn-info btn-sm btn-sm" %>
		<% end %>
	  </div>
	</nav>
	<!--END-->


	<div class="container">
	<% if notice %>
	<div class="alert alert-dismissible alert-success"><%= notice %></div>
	<% end %>
	<% if alert %>
	<div class="alert alert-dismissible alert-danger"><%= alert %></div>
	<% end %>

	</div>
	<div class="row">
	  <div class="col"></div>
	  <%= yield %>
	  <div class="col"></div>
	</div>
  </body>
</html>